name: meta_shop
description: Meta Shop Online Store

publish_to: 'none'

version: 2.0.2

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  hovering: ^1.0.4
  intl: ^0.18.1
  get: ^4.6.5
  font_awesome_flutter: ^10.5.0
  custom_navigation_bar: ^0.8.2
  flutter_switch: ^0.3.2
  flutter_svg: ^2.0.6
  syncfusion_flutter_sliders: ^22.2.9
  get_storage: ^2.0.3
  image_picker: ^1.0.2
  url_launcher: ^6.1.11
  permission_handler: ^10.3.0
  lazy_load_scrollview: 1.3.0
  cached_network_image: ^3.2.2
  flutter_native_splash: ^2.3.1
  cupertino_icons: ^1.0.5
  onesignal_flutter: ^3.4.2
  shimmer: ^3.0.0
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  google_sign_in: ^6.1.4
  video_player: ^2.5.1
  webview_flutter: ^2.5.1
  http: ^1.1.0
  device_info_plus: ^9.0.2
  cool_dropdown: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/cart.svg
    - assets/icons/category.png
    - assets/icons/customer_service.svg
    - assets/icons/delivery_truck.png
    - assets/icons/package.png
    - assets/icons/placeHolder.png
    - assets/icons/secure_payment.png
    - assets/photos/Background_1.png
    - assets/photos/adidas_logo.png
    - assets/photos/all_car_accessories.png
    - assets/photos/car_toy.png
    - assets/photos/car_toy_2.jpg
    - assets/photos/car_toy_3.jpg
    - assets/photos/car_toy_4.jpg
    - assets/photos/charcoal_grill.png
    - assets/photos/fila_logo.png
    - assets/photos/grill_2.jpg
    - assets/photos/grill_3.jpg
    - assets/photos/grill_4.jpg
    - assets/photos/lmmea.png
    - assets/photos/login_2.png
    - assets/photos/login_background.png
    - assets/photos/logo.png
    - assets/photos/logo_2.jpg
    - assets/photos/mechanic_tools.png
    - assets/photos/medical_equipment.png
    - assets/photos/nike_logo.png
    - assets/photos/phone_accessories.png
    - assets/photos/puma_logo.png
    - assets/photos/sporting_goods.png
    - assets/photos/vans_logo.png
    - assets/photos/wooden_educational_toy.png
    - shorebird.yaml
    - shorebird.yaml
